Update 0.7.1
AnacondaRecipes/openapi-spec-validator-feedstock pull request #3
Opened 2024-04-12 10:28 UTC by JamesRobertsonGames

openapi-spec-validator 0.7.1 

**Destination channel:** defaults

### Links

- [PKG-4452](https://anaconda.atlassian.net/browse/PKG-4452) 
- [Upstream repository](https://github.com/p1c2u/openapi-spec-validator)
- [Upstream changelog/diff](https://github.com/python-openapi/openapi-spec-validator/releases/tag/0.7.1)
- Relevant dependency PRs:
  - moto

### Explanation of changes:
- Update version, remove noarch, improve testing, pass lint

2024-04-12 10:29 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_88fotrils2/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:54: documentation_specifies_language: Use the generic link, not a language specific one
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-04-12 12:43 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - openapi-schema-validator
I think we should explicitly pin dependencies, see https://github.com/python-openapi/openapi-spec-validator/blob/409da9d242e35f17e325669c055277c2d2976177/pyproject.toml#L55-L60

2024-04-12 12:46 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_d2do_gkhs0/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:55: documentation_specifies_language: Use the generic link, not a language specific one

===== ERRORS =====
- clone/recipe/meta.yaml:32: remove_python_pinning: On arch specific packages, python deps should not be constrained.
===== Final Report: =====
1 Error and 1 Warning were found

</details>

2024-04-12 12:47 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_f486z4ly1h/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:54: documentation_specifies_language: Use the generic link, not a language specific one
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-04-12 12:55 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_fd5ng2rq6t/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:54: documentation_specifies_language: Use the generic link, not a language specific one
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-04-12 13:09 UTC, skupr-anaconda approved these changes

2024-04-12 20:37 UTC, JeanChristopheMorinPerso requested changes

2024-04-12 20:37 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    - lazy-object-proxy >=1.7.1
```suggestion
    - lazy-object-proxy >=1.7.1,<2
```
https://inspector.pypi.io/project/openapi-spec-validator/0.7.1/packages/2b/4d/e744fff95aaf3aeafc968d5ba7297c8cda0d1ecb8e3acd21b25adae4d835/openapi_spec_validator-0.7.1-py3-none-any.whl/openapi_spec_validator-0.7.1.dist-info/METADATA#line.27

2024-04-12 20:37 UTC, JeanChristopheMorinPerso commented on recipe/meta.yaml
> +    # keep in sync with the poetry-generated setup.py
I feel like this should be removed?

2024-04-15 09:30 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_c0sbktj01a/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:54: documentation_specifies_language: Use the generic link, not a language specific one
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-04-15 11:33 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_bb9f4q8ejf/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:53: documentation_specifies_language: Use the generic link, not a language specific one
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-04-15 13:46 UTC, cbouss approved these changes

2024-04-15 13:49 UTC, merged

2024-04-15 13:50 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(124): `conda run conda-lint /tmp/abs_e0686xp50d/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:53: documentation_specifies_language: Use the generic link, not a language specific one
===== Final Report: =====
0 Errors and 1 Warning were found

</details>